version: "2.0"

services:
  web:
    image: tomcat:8.5.58-jdk15-openjdk-slim-buster
    ports:
      - "80:8080"
    volumes:
      - artifact:/usr/local/tomcat/webapps/ROOT

  maven:
    build: ./maven
    volumes:
      - artifact:/artifact

volumes:
  artifact: